name: Common CI
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo build
  Test:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo test
  Dev-Deploy:
    runs-on: self-hosted
    needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          repository: manjudevopszone/roboshop-helm
      - name: Deploy using helm
        run: |
          export PATH=/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin 
          make component=${{ inputs.component }} env=dev